config/routes.rb
Rails.application.routes.draw do
  resources :users,        only: [:show, :new, :create]
  resources :sessions,     only: [:new, :create, :destroy]
  resources :groups,       only: [:index, :show, :new, :create]
  resources :transactions, only: [:index, :new, :create]
  get       '/external',   to: 'transactions#external'
  root      'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :transactions

  scope :sort_alphabetical, -> { order(name: :asc) }

  validates :name,
            presence: true,
            uniqueness: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :group, optional: true

  scope :sort_most_recent, -> { order(created_at: :desc) }
  scope :with_group, -> { where.not('group_id' => nil) }
  scope :without_group, -> { where('group_id' => nil) }

  validates :name,
            presence: true,
            length: { minimum: 3 }

  validates :amount,
            presence: true,
            length: { maximum: 12 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :transactions

  # active storage
  has_one_attached :image

  validates :name,
            presence: true,
            uniqueness: true,
            length: { in: 3..12 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  add_flash_types :success

  def require_login
    redirect_to new_session_path, notice: 'You must be logged' unless current_user
  end

  def not_logged
    redirect_to user_path(cookies[:current_user_id]), success: 'You already logged' if current_user
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_login, only: %i[index show new create]

  def index
    @groups = Group.all.sort_alphabetical
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    return redirect_to groups_path if @group.save

    flash[:errors] = @group.errors.full_messages
    redirect_to new_group_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # login page
  def new; end

  # login button
  def create
    if (userx = User.find_by(name: params[:username_in]))

      cookies[:current_user_id] = {
        value: userx.id, expires: Time.now + 7200
      }

      redirect_to root_path,
                  notice: 'Login successfully'
    else
      redirect_to new_session_path,
                  alert: 'Name not recognized'
    end
  end

  # logout button
  def destroy
    cookies.delete(:current_user_id)

    redirect_to new_session_path
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :require_login, only: %i[index new create external]

  def index
    @transactions = current_user.transactions
      .sort_most_recent.includes(:group)
    # .with_group.sort_most_recent.includes(:group)
  end

  def new
    @transaction = current_user.transactions.build
    @groups = Group.all
  end

  def create
    @transaction = current_user.transactions.build(transaction_params)
    return redirect_to transactions_path if @transaction.save

    flash[:errors] = @transaction.errors.full_messages
    redirect_to new_transaction_path
  end

  def external
    @external_trans = current_user.transactions.without_group.sort_most_recent.includes(:group)
  end

  private

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :group_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: %i[show]
  before_action :not_logged, only: %i[new create index]

  # home page
  def index; end

  # user profile
  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      cookies[:current_user_id] = @user.id

      redirect_to user_path(cookies[:current_user_id]),
                  notice: 'Account successfully created.'
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages(type, style = 'alert-danger')
    flash.map do |_msg|
      content_tag(:p, type, class: "alert #{style}") if type
    end.join.html_safe
  end

  def flash_errors
    return unless flash[:errors]

    content_tag(:ul) do
      flash[:errors].map do |error|
        content_tag(:li, error, class: 'alert alert-danger')
      end.join.html_safe
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  # index - list all groups
  def groups_list(groups)
    content_tag(:div, class: 'list') do
      groups.map do |line|
        concat(
          content_tag(:div, class: 'list-item') do
            content_tag(:p, (link_to image_tag(line.icon, class: 'icon float'),
                                     group_path(line.id), class: 'dark-text')) +
            content_tag(:p, (link_to line.name, group_path(line.id), class: 'dark-text')) +
            tag(:hr) +
            content_tag(:p, line.created_at.strftime('%d %b %Y'), class: 'dark-text') +
            tag(:br)
          end
        )
      end
    end
  end

  # show - all transactions from a group
  def transactions_of(group_trans)
    content_tag(:div, class: 'list') do
      group_trans.map do |line|
        concat(
          content_tag(:div, class: 'list-item p-1') do
            concat(
              content_tag(:div, class: 'flex space-between') do
                content_tag(:p, line.name, class: 'dark-text') +
                content_tag(:p, "$#{number_with_precision(line.amount, precision: 2)}",
                            class: 'dark-text')
              end
            )
            concat(
              content_tag(:div) do
                tag(:br) +
                content_tag(:p, "#{line.created_at.strftime('%d %b %Y')}
                  • by #{line.user.name}", class: 'dark-text')
              end
            )
          end
        )
      end
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    current_user = User.find_by(id: cookies[:current_user_id])
    current_user
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def total_amount_with_group
    Transaction.with_group.sum(:amount)
  end

  def total_amount_without_group
    Transaction.without_group.sum(:amount)
  end

  def transactions_list(query)
    content_tag(:div, class: 'list') do
      query.map do |line|
        concat(
          content_tag(:div, class: 'list-item') do
            unless line.group.nil?
              concat(
                content_tag(:p, (link_to image_tag(line.group.icon, class: 'icon float'),
                                         group_path(line.group.id), class: 'dark-text'))
              )
            end
            concat(
              content_tag(:div, class: 'flex space-between') do
                content_tag(:p, line.name, class: 'dark-text') +
                content_tag(:p, "$#{number_with_precision(line.amount, precision: 2)}", class: 'dark-text')
              end
            )
            concat(
              tag(:hr) +
              content_tag(:p, line.created_at.strftime('%d %b %Y'), class: 'dark-text')
            )
          end
        )
      end
    end
  end

  def transactions_ext_list(query)
    content_tag(:div, class: 'list') do
      query.map do |line|
        concat(
          content_tag(:div, class: 'list-item') do
            concat(
              content_tag(:div, class: 'flex space-between') do
                content_tag(:p, line.name, class: 'dark-text') +
                content_tag(:p, "$#{number_with_precision(line.amount, precision: 2)}",
                            class: 'dark-text')
              end
            )
            concat(
              tag(:hr) +
              content_tag(:p, line.created_at.strftime('%d %b %Y'), class: 'dark-text')
            )
          end
        )
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_username
    return unless current_user

    content_tag(:h1, current_user.name)
  end

  def display_avatar(who)
    image_tag(who.image, class: 'avatar center-space') if who.image.attached?
  end
end

app/views/groups/_new_group.html.erb
<%= render partial: "layouts/errors" %>

<%= form_with(model: @group) do |form| %>
  <%= form.label(:name, 'Name: ') %>
  <%= form.text_field(:name) %><br>

  <%= form.label(:icon, 'Icon link: ') %>
  <%= form.text_field(:icon) %>

  <div class="flex btn-bg">
    <%= form.submit('NEW GROUP', class: 'btn btn-bg') %>
  </div>
<% end %>

app/views/groups/index.html.erb
<div class="flex space-between">
  <%= link_to '<span class="material-icons">arrow_back</span>'.html_safe,
    user_path(current_user.id) %>
  <h1>GROUPS</h1>
  <%= link_to '<span class="material-icons">power_settings_new</span>'.html_safe,
    new_session_path, method: :delete %>
</div>

<%= groups_list(@groups) %>

<div class="flex btn-bg">
  <%= link_to 'CREATE NEW', new_group_path, :class => "btn" %>
</div>

app/views/groups/new.html.erb
<div class="flex space-between">
  <%= link_to '<span class="material-icons">arrow_back</span>'.html_safe,
    groups_path %>
  <h1>NEW GROUP</h1>
  <%= link_to '<span class="material-icons">power_settings_new</span>'.html_safe,
    new_session_path, method: :delete %>
</div>

<%= render partial: "new_group" %>

app/views/groups/show.html.erb
<div class="flex space-between">
  <%= link_to '<span class="material-icons">arrow_back</span>'.html_safe,
    groups_path %>
  <h1><%= @group.name %> transactions</h1>
  <%= link_to '<span class="material-icons">power_settings_new</span>'.html_safe,
    new_session_path, method: :delete %>
</div>

<div class="flex space-between align-center board">
  <h3>Total amount</h3>

  <p>$<%= number_with_precision(
    @group.transactions.sum(:amount), :precision => 2) %>
  </p>
</div>

<%= transactions_of(@group.transactions) %>

<div class="flex btn-bg">
  <%= link_to 'NEW TRANSACTION', new_transaction_path,
    :class => "btn" %>
</div>

app/views/layouts/_errors.html.erb
<%= flash_errors %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Thiago Miranda">
    <title>Wallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="image" property="og:image" content="https://imagizer.imageshack.com/img924/2408/yO7wH8.png">
    <meta name="description" property="og:description" content="A mobile web app, to manage your personal cash flow.">
  </head>

  <body class="container">
    <%= flash_messages(notice) %>
    <%= flash_messages(alert) %>
    <%= flash_messages(success, 'alert-success') %>

    <%= yield %>
  </body>
</html>

app/views/transactions/_new_transaction.html.erb
<%= render partial: "layouts/errors" %>

<%= form_with(model: @transaction) do |form| %>
  <%= form.label(:name, 'Subject: ') %>
  <%= form.text_field(:name) %>

  <%= form.label(:amount, 'Amount: ') %>
  <%= form.number_field(:amount) %>

  <%= form.label(:group_id, 'Group: ') %>
  <%= form.select(:group_id, nil, { include_blank: 'None' }) do %>
    <% @groups.each do |group| %>
      <%= content_tag(:option, group[:name], value: group[:id]) %>
    <% end %>
  <% end %>

  <div class="flex btn-bg">
    <%= form.submit('GO', class: 'btn btn-bg') %>
  </div>
<% end %>

app/views/transactions/external.html.erb
<div class="flex space-between">
  <%= link_to '<span class="material-icons">arrow_back</span>'.html_safe,
    user_path(current_user.id) %>
  <h1>EXTERNAL TRANS.</h1>
  <%= link_to '<span class="material-icons">power_settings_new</span>'.html_safe,
  new_session_path, method: :delete %>
</div>

<div class="flex space-between align-center board">
  <h3>Total amount</h3>

  <p>$<%= number_with_precision(
    current_user.transactions.without_group.sum(:amount),
    :precision => 2) %></p>
</div>

<%= transactions_ext_list(@external_trans) %>

<div class="flex btn-bg">
  <%= link_to 'ADD NEW', new_transaction_path, :class => "btn" %>
</div>

app/views/transactions/index.html.erb
<div class="flex space-between">
  <%= link_to '<span class="material-icons">arrow_back</span>'.html_safe,
    user_path(current_user.id) %>
  <h1>TRANSACTIONS</h1>
  <%= link_to '<span class="material-icons">power_settings_new</span>'.html_safe,
    new_session_path, method: :delete %>
</div>

<div class="flex space-between align-center board">
  <h3>Total amount</h3>

  <p>$<%= number_with_precision(
    current_user.transactions.with_group.sum(:amount),
    :precision => 2) %></p>
</div>

<%= transactions_list(@transactions) %>

<div class="flex btn-bg">
  <%= link_to 'ADD NEW', new_transaction_path, :class => "btn" %>
</div>

app/views/transactions/new.html.erb
<div class="flex space-between">
  <%= link_to '<span class="material-icons">arrow_back</span>'.html_safe,
    transactions_path %>
  <h1>NEW TRANSACTION</h1>
  <%= link_to '<span class="material-icons">power_settings_new</span>'.html_safe,
    new_session_path, method: :delete %>
</div>

<%= render partial: "new_transaction" %>

app/views/users/_new_user.html.erb
<%= render partial: "layouts/errors" %>

<%= form_with(model: @user) do |form| %>
  <%= form.label(:name, 'Your username: ') %>
  <%= form.text_field(:name) %><br>

  <%= form.label(:image, 'Upload avatar: ') %>
  <%= form.file_field(:image) %>

  <div class="flex btn-bg">
    <%= form.submit('CREATE ACCOUNT', class: 'btn btn-bg') %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="sep">
  <h1>Welcome to Wallet</h1>
</div>

<div class="flex btn-bg">
  <%= link_to 'LOGIN', new_session_path, :class => 'btn' %>
</div>

<p class="sep">OR</p>

<div class="flex btn-bg">
  <%= link_to 'REGISTER', new_user_path, :class => 'btn' %>
</div>

app/views/users/new.html.erb
<div class="flex space-between">
  <%= link_to '<span class="material-icons">arrow_back</span>'.html_safe, transactions_path %>
  <h1>NEW USER</h1><span></span>
</div>

<%= render partial: "new_user" %>

app/views/users/show.html.erb
<div class="flex dir-col">
  <%= display_avatar(current_user) %>

  <h1 class="center-space"><%= current_user.name %></h1>
</div>

<ul>
  <li><%= link_to 'All my transactions', transactions_path %><br></li>
  <hr>

  <li><%= link_to 'All my external transactions', external_path %><br></li>
  <hr>

  <li><%= link_to 'All Groups', groups_path %></li>
</ul>